version: '3'

services:
  mysql:
    image: mysql:8.0.34
    environment:
      MYSQL_ROOT_PASSWORD: tajnehaslo
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    networks:
      - ogloszex-network

  ogloszex-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - ogloszex-network
    depends_on:
      - mysql

networks:
  ogloszex-network:
    driver: bridge
