version: '3'
services:
  db:
    image: mysql:8.0.35
    container_name: mysql
    environment:
      MYSQL_DATABASE: ogloszex
      MYSQL_USER: root
      MYSQL_PASSWORD: tajnehaslo
      MYSQL_ROOT_PASSWORD: tajnehaslo
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapp
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ogloszex
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: tajnehaslo