spring:
  datasource:
    url: jdbc:h2:mem:ogloszex;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: root
    password: tajnehaslo
  liquibase:
    contexts: prod
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true