spring:
  datasource:
    username: root
    password: tajnehaslo
    url: jdbc:mysql://mysql:3306/ogloszex
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/ogloszex
  liquibase:
    contexts: prod